POST http://localhost:3003/api/blogs
Content-type: application/json

{
    "title": "Testing while Refactoring - pt3",
    "author": "Author Refactor3",
    "url": "http://localhost:3003",
    "likes": 3
}